# Generated by Django 3.2.5 on 2021-12-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_project',
            name='url',
            field=models.CharField(default='', max_length=50, verbose_name='url'),
        ),
    ]
